export const products = [
  {
    id: "1",
    name: "Máquina de Tatuar Profesional",
    price: 250.0,
    image: "/placeholder.png?height=200&width=200&text=Máquina+Tatuar",
    description: "Máquina rotativa de alta calidad para líneas y sombreados precisos. Ideal para profesionales.",
  },
  {
    id: "2",
    name: "Kit de Tintas Premium (12 colores)",
    price: 120.0,
    image: "/placeholder.png?height=200&width=200&text=Tintas+Premium",
    description: "Set de 12 tintas vibrantes y duraderas, aptas para todo tipo de piel. Colores intensos.",
  },
  {
    id: "3",
    name: "Agujas Desechables (Caja de 50)",
    price: 45.0,
    image: "/placeholder.png?height=200&width=200&text=Agujas+Desechables",
    description: "Caja de 50 agujas estériles de acero inoxidable, varios tamaños disponibles.",
  },
  {
    id: "4",
    name: "Fuente de Poder Digital",
    price: 90.0,
    image: "/placeholder.png?height=200&width=200&text=Fuente+Poder",
    description: "Fuente de poder compacta con pantalla digital, control de voltaje preciso.",
  },
  {
    id: "5",
    name: "Piel Sintética para Práctica",
    price: 15.0,
    image: "/placeholder.png?height=200&width=200&text=Piel+Sintética",
    description: "Piel sintética de alta densidad para practicar técnicas de tatuaje. Reutilizable.",
  },
  {
    id: "6",
    name: "Vaselina para Tatuajes (500g)",
    price: 20.0,
    image: "/placeholder.png?height=200&width=200&text=Vaselina+Tatuajes",
    description: "Vaselina especial para tatuajes, hidrata y protege la piel durante el proceso.",
  },
  {
    id: "7",
    name: "Guantes de Nitrilo (Caja de 100)",
    price: 25.0,
    image: "/placeholder.png?height=200&width=200&text=Guantes+Nitrilo",
    description: "Caja de 100 guantes de nitrilo, resistentes y cómodos para uso profesional.",
  },
  {
    id: "8",
    name: "Plantillas de Transferencia",
    price: 10.0,
    image: "/placeholder.png?height=200&width=200&text=Plantillas+Transferencia",
    description: "Papel de transferencia para crear diseños precisos en la piel antes de tatuar.",
  },
]
